// display actions
export const UPDATE_DISPLAY = 'UPDATE_DISPLAY';
export const SET_PIXELS_PER_ROW = 'SET_PIXELS_PER_ROW';
export const SET_PIXELS_PIXEL_DENSITY = 'SET_PIXELS_PIXEL_DENSITY';

// dev actions

export const ADD_TO_LIT_PIXEL_ARRAY = 'ADD_TO_LIT_PIXEL_ARRAY';
export const REMOVE_FROM_LIT_PIXEL_ARRAY = 'REMOVE_FROM_TO_LIT_PIXEL_ARRAY';

// character state actions

export const SET_DIRECTION = 'CHANGE_DIRECTION';
export const SET_ENERGY = 'UPDATE_ENERGY';
export const SET_MONSTER_BLUEPRINT = 'SET_MONSTER_BLUEPRINT';
export const SET_CURRENT_ANIMATION_FRAME = 'NEXT_ANIMATION_FRAME';



